name: Test

on: [push, pull_request]

jobs:
  test:
    name: RSpec
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.3', '2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', jruby ]
        gemfile: [ gemfiles/carrierwave-2.gemfile ]
        include:
          - ruby: '2.1'
            gemfile: gemfiles/carrierwave-1.gemfile
          - ruby: '2.2'
            gemfile: gemfiles/carrierwave-1.gemfile
          - ruby: '3.2'
            gemfile: gemfiles/carrierwave-master.gemfile
    runs-on: ubuntu-20.04
    permissions:
      id-token: 'write'
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      GCLOUD_BUCKET: ${{ secrets.GCLOUD_BUCKET }}
      JRUBY_OPTS: --debug
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Setup Google Cloud Platform service account credential
      run: |
        mkdir -p ${HOME}/.config/gcloud
        echo "${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}" | base64 -d > ${HOME}/.config/gcloud/application_default_credentials.json
    - name: Set BUILD_ID
      run: echo "BUILD_ID=$(echo '${{ github.run_id }}${{ toJSON(matrix) }}' | shasum | cut -c 1-8)" >> $GITHUB_ENV
    - name: Run RSpec
      run: bundle exec rake

